--7
CREATE SEQUENCE dept_id_seq
  START WITH 200
  INCREMENT BY 10
  MAXVALUE 1000;

---> ANTES CRIE A TABELA DEPT (VAZIA => WHERE 1=2) COM BASE NA TABELA DEPARTMENTS

CREATE TABLE DEPT
AS 
SELECT DEPARTMENT_ID DEPT_ID, DEPARTMENT_NAME NAME
FROM DEPARTMENTS
WHERE 1=2;

--8
INSERT INTO dept
VALUES (dept_id_seq.nextval, 'Education');

INSERT INTO dept
VALUES (dept_id_seq.nextval, 'Administration');

--9
CREATE INDEX dept_name_idx ON dept (name);

--10
CREATE SYNONYM emp FOR EMPLOYEES;
 